import type { Lead, LeadStage, VendorProduct } from "./types";

// ─── Base timestamps (June 2026) ──────────────────────────────────────────────
const N = 1781000000;
const H = 3600;
const D = 86400;

// ─── Stage configuration ──────────────────────────────────────────────────────
export const STAGE_CONFIG: Record<
  LeadStage,
  { label: string; short: string; color: string; bg: string; border: string; dot: string }
> = {
  NEW_INQUIRY:          { label: "New Inquiry",          short: "New",       color: "text-blue-700",   bg: "bg-blue-500/10",   border: "border-blue-400/30",   dot: "bg-blue-500"   },
  REQUIREMENT_ANALYSIS: { label: "Req. Analysis",        short: "Analysis",  color: "text-indigo-700", bg: "bg-indigo-500/10", border: "border-indigo-400/30", dot: "bg-indigo-500" },
  VENDOR_SOURCING:      { label: "Vendor Sourcing",      short: "Sourcing",  color: "text-violet-700", bg: "bg-violet-500/10", border: "border-violet-400/30", dot: "bg-violet-500" },
  QUOTATION_SENT:       { label: "Quotation Sent",       short: "Quoted",    color: "text-amber-700",  bg: "bg-amber-500/10",  border: "border-amber-400/30",  dot: "bg-amber-500"  },
  NEGOTIATION:          { label: "Negotiation",          short: "Nego.",     color: "text-orange-700", bg: "bg-orange-500/10", border: "border-orange-400/30", dot: "bg-orange-500" },
  CONFIRMED:            { label: "Confirmed",            short: "Confirmed", color: "text-emerald-700",bg: "bg-emerald-500/10",border: "border-emerald-400/30",dot: "bg-emerald-500"},
  PROCUREMENT:          { label: "Procurement",          short: "Procure",   color: "text-teal-700",   bg: "bg-teal-500/10",   border: "border-teal-400/30",   dot: "bg-teal-500"   },
  DELIVERED:            { label: "Delivered",            short: "Delivered", color: "text-green-700",  bg: "bg-green-500/10",  border: "border-green-400/30",  dot: "bg-green-500"  },
  CLOSED:               { label: "Closed",               short: "Closed",    color: "text-slate-500",  bg: "bg-slate-500/8",   border: "border-slate-400/20",  dot: "bg-slate-400"  },
};

export const PIPELINE_STAGES: LeadStage[] = [
  "NEW_INQUIRY","REQUIREMENT_ANALYSIS","VENDOR_SOURCING","QUOTATION_SENT",
  "NEGOTIATION","CONFIRMED","PROCUREMENT","DELIVERED","CLOSED",
];

export const PRIORITY_CONFIG = {
  low:    { label: "Low",    dot: "bg-sky-400",    text: "text-sky-600"    },
  medium: { label: "Medium", dot: "bg-amber-400",  text: "text-amber-700"  },
  high:   { label: "High",   dot: "bg-orange-500", text: "text-orange-700" },
  urgent: { label: "Urgent", dot: "bg-red-500",    text: "text-red-700",   pulse: true },
};

export const ACTIVITY_ICON_MAP: Record<string, string> = {
  note: "MessageSquare", call: "PhoneCall", email: "Mail",
  stage_change: "ArrowRight", quotation_sent: "FileText",
  system: "Zap", reminder_set: "Clock",
};

// ─── Mock Leads ───────────────────────────────────────────────────────────────
export const MOCK_LEADS: Lead[] = [
  {
    id: "l1",
    customerName: "Ananya Kapoor",
    company: "AK Interiors",
    email: "ananya@akinteriors.in",
    phone: "+91 98204 11234",
    city: "Mumbai",
    stage: "NEW_INQUIRY",
    priority: "high",
    inquiryText: "Hi, I'm an interior designer working on a luxury residential project in Bandra West. I need premium white marble for the living area and master bedroom — approximately 800 sq ft total. Looking for Italian origin if possible. Can you help?",
    aiSummary: "Interior designer sourcing premium Italian white marble for a luxury residential project in Bandra West, Mumbai. Requires ≈800 sq ft across living area + master bedroom. Budget estimate ₹5–6L. AK Interiors typically handles ₹50L+ projects — high conversion probability. Calacatta Oro is the likely match. Contacted 2 hours ago; recommend responding within 4 hours with a curated deck.",
    materialRequested: "Italian white marble (Calacatta preferred)",
    applicationArea: "Flooring",
    areaRequired: "800 sq ft",
    budget: "₹5–6 lakh",
    createdAt: N - 2 * H,
    updatedAt: N - 2 * H,
    assignedTo: "Sneha Agarwal",
    activityLog: [
      { id: "a1-1", type: "system", text: "Lead created from website inquiry form.", author: "System", timestamp: N - 2 * H },
    ],
  },
  {
    id: "l2",
    customerName: "Vikram Shah",
    company: "Shah Builders",
    email: "vikram.shah@shahbuilders.com",
    phone: "+91 90020 55678",
    city: "Pune",
    stage: "REQUIREMENT_ANALYSIS",
    priority: "urgent",
    inquiryText: "We are developing a new corporate office park in Kharadi, Pune and need granite flooring and countertops for 5000 sq ft. Delivery timeline is critical — 3 weeks max. Can you support this?",
    aiSummary: "Large-scale commercial project. Shah Builders (repeat customer, Order #STN-2022-014) needs granite flooring + countertops for a 5,000 sq ft corporate park in Kharadi, Pune. Budget ₹25–30L. Hard delivery deadline: 3 weeks. Vikram is the procurement head — direct decision maker. Prioritise immediately. Kashmir White and Baltic Brown are strong catalog matches for this scale and budget.",
    materialRequested: "Granite flooring + countertops",
    applicationArea: "Commercial Flooring & Countertops",
    areaRequired: "5000 sq ft",
    budget: "₹25–30 lakh",
    createdAt: N - 5 * D,
    updatedAt: N - 4 * H,
    assignedTo: "Rohan Desai",
    activityLog: [
      { id: "a2-1", type: "system",       text: "Lead created from website inquiry form.", author: "System",        timestamp: N - 5 * D },
      { id: "a2-2", type: "call",         text: "Initial call with Vikram Shah. Confirmed 5,000 sq ft granite requirement across 2 floors. Tight 3-week delivery window.", author: "Rohan Desai",  timestamp: N - 4 * D - 6 * H },
      { id: "a2-3", type: "note",         text: "Repeat customer — see Order #STN-2022-014 (Travertine, 1,200 sq ft, delivered on time). Excellent payment history.", author: "Sneha Agarwal", timestamp: N - 4 * D },
      { id: "a2-4", type: "stage_change", text: "Stage moved: New Inquiry → Requirement Analysis", author: "Rohan Desai",  timestamp: N - 4 * H },
    ],
  },
  {
    id: "l3",
    customerName: "Priya Nair",
    email: "priya.nair88@gmail.com",
    phone: "+91 94463 77890",
    city: "Kochi",
    stage: "VENDOR_SOURCING",
    priority: "medium",
    inquiryText: "I'm renovating my new flat's kitchen and 2 bathrooms. Looking for quartz countertops — preferably white or light grey. Total area around 120 sq ft. Budget is a bit tight. Please advise.",
    aiSummary: "Homeowner renovating kitchen and 2 bathrooms in a new flat. Needs quartz countertops (≈120 sq ft), prefers white or light grey. Budget-conscious but committed buyer — has shortlisted Stellar White Quartz and Desert Sand from the catalog. Decision timeline: 2 weeks. Priya is detail-oriented; include a product spec sheet and care guide with the quotation.",
    materialRequested: "White / light grey quartz countertops",
    applicationArea: "Countertops",
    areaRequired: "120 sq ft",
    budget: "₹1.5–2 lakh",
    createdAt: N - 8 * D,
    updatedAt: N - 1 * D,
    assignedTo: "Sneha Agarwal",
    followUpDate: "2026-06-15",
    followUpNote: "Call to confirm which quartz option she prefers before raising quotation.",
    activityLog: [
      { id: "a3-1", type: "system",       text: "Lead created from website inquiry form.", author: "System",        timestamp: N - 8 * D },
      { id: "a3-2", type: "email",        text: "Sent curated product deck (Stellar White, Desert Sand, Kashmir White) with pricing and spec sheets.", author: "Sneha Agarwal", timestamp: N - 7 * D },
      { id: "a3-3", type: "stage_change", text: "Stage moved: New Inquiry → Requirement Analysis", author: "Sneha Agarwal", timestamp: N - 7 * D },
      { id: "a3-4", type: "call",         text: "Priya shortlisted Stellar White Quartz and Desert Sand. Needs pricing by Friday.", author: "Sneha Agarwal", timestamp: N - 3 * D },
      { id: "a3-5", type: "stage_change", text: "Stage moved: Requirement Analysis → Vendor Sourcing", author: "Sneha Agarwal", timestamp: N - 1 * D },
      { id: "a3-6", type: "reminder_set", text: "Follow-up reminder set for 15 Jun 2026.", author: "Sneha Agarwal", timestamp: N - 1 * D },
    ],
  },
  {
    id: "l4",
    customerName: "Arjun Mehta",
    company: "Studio Meridian",
    email: "arjun@studiomeridian.in",
    phone: "+91 98765 43210",
    city: "Mumbai",
    stage: "QUOTATION_SENT",
    priority: "high",
    inquiryText: "We're specifying premium finishes for a luxury villa in Juhu. Need Calacatta Oro for the main floor (~800 sq ft) and Kashmir White for feature walls (~400 sq ft). Looking for a combined quotation with delivery. Can you arrange slab samples first?",
    aiSummary: "Principal architect at Studio Meridian specifying luxury finishes for a Juhu villa. Needs Calacatta Oro (floors, 800 sq ft) + Kashmir White Granite (walls, 400 sq ft). Quotation STN-2024-0038 sent 2 days ago — awaiting response. During the pre-quote call, Arjun indicated budget is 'flexible for the right quality.' Recommend a follow-up call today. High closure probability.",
    materialRequested: "Calacatta Oro + Kashmir White Granite",
    applicationArea: "Flooring + Wall Cladding",
    areaRequired: "1200 sq ft",
    budget: "₹8–12 lakh",
    createdAt: N - 14 * D,
    updatedAt: N - 2 * D,
    assignedTo: "Rohan Desai",
    activityLog: [
      { id: "a4-1", type: "system",        text: "Lead created from email inquiry.", author: "System",       timestamp: N - 14 * D },
      { id: "a4-2", type: "call",          text: "Intro call with Arjun. Confirmed spec: Calacatta (floor) + Kashmir White (walls) for Juhu villa.", author: "Rohan Desai", timestamp: N - 12 * D },
      { id: "a4-3", type: "stage_change",  text: "Stage moved: New Inquiry → Requirement Analysis", author: "Rohan Desai", timestamp: N - 12 * D },
      { id: "a4-4", type: "note",          text: "Sample delivery arranged: Calacatta 30×30 and Kashmir White 30×30 samples dispatched via BlueDart.", author: "Rohan Desai", timestamp: N - 10 * D },
      { id: "a4-5", type: "stage_change",  text: "Stage moved: Requirement Analysis → Vendor Sourcing", author: "Rohan Desai", timestamp: N - 7 * D },
      { id: "a4-6", type: "quotation_sent",text: "Quotation STN-2024-0038 (₹9,84,000) sent via email. Valid 30 days.", author: "Rohan Desai", timestamp: N - 2 * D },
      { id: "a4-7", type: "stage_change",  text: "Stage moved: Vendor Sourcing → Quotation Sent", author: "Rohan Desai", timestamp: N - 2 * D },
    ],
  },
  {
    id: "l5",
    customerName: "Sunita Reddy",
    company: "Reddy Hospitality",
    email: "sunita.reddy@reddyhotels.com",
    phone: "+91 91234 56789",
    city: "Hyderabad",
    stage: "NEGOTIATION",
    priority: "urgent",
    inquiryText: "We are upgrading the lobby and corridors of our 4-star property. Total area is around 3,000 sq ft. Looking for a premium dark granite and a beige marble combination. Need competitive pricing as this is a large volume order.",
    aiSummary: "Hotel renovation project — high value, time-sensitive. Reddy Hospitality is upgrading lobby + corridors (3,000 sq ft) with black granite and beige marble. Initial quote: ₹19,80,000. Customer requested 12% discount; current counter-offer is 8% off + complimentary delivery (saves ~₹18,000). Decision expected by EOD Friday. This is the largest pending order in Q2 — approve the 8% discount to close.",
    materialRequested: "Black Absolute + Crema Marfil",
    applicationArea: "Commercial Flooring",
    areaRequired: "3000 sq ft",
    budget: "₹18–22 lakh",
    createdAt: N - 21 * D,
    updatedAt: N - 6 * H,
    assignedTo: "Sneha Agarwal",
    activityLog: [
      { id: "a5-1", type: "system",        text: "Lead created from inbound call.", author: "System",        timestamp: N - 21 * D },
      { id: "a5-2", type: "call",          text: "Requirements confirmed: 2,000 sq ft Black Absolute + 1,000 sq ft Crema Marfil. Delivery in 4 weeks.", author: "Sneha Agarwal", timestamp: N - 19 * D },
      { id: "a5-3", type: "stage_change",  text: "Stage moved: New Inquiry → Requirement Analysis", author: "Sneha Agarwal", timestamp: N - 19 * D },
      { id: "a5-4", type: "stage_change",  text: "Stage moved: Requirement Analysis → Vendor Sourcing", author: "Sneha Agarwal", timestamp: N - 15 * D },
      { id: "a5-5", type: "quotation_sent",text: "Quotation STN-2024-0035 (₹19,80,000) sent. Valid 21 days.", author: "Sneha Agarwal", timestamp: N - 10 * D },
      { id: "a5-6", type: "stage_change",  text: "Stage moved: Quotation Sent → Negotiation", author: "Sneha Agarwal", timestamp: N - 7 * D },
      { id: "a5-7", type: "call",          text: "Sunita requested 12% discount. Counter-offered 8% off + free delivery. Awaiting approval from her GM.", author: "Sneha Agarwal", timestamp: N - 6 * H },
    ],
  },
  {
    id: "l6",
    customerName: "Deepak Sharma",
    company: "TechPark Infra",
    email: "deepak.sharma@techparkinfra.com",
    phone: "+91 95550 12345",
    city: "Bangalore",
    stage: "CONFIRMED",
    priority: "medium",
    inquiryText: "Office renovation – need Travertine Classic Beige for 600 sq ft of flooring. I've seen your catalog and this is our first choice. Please send quotation and payment details.",
    aiSummary: "Order confirmed and advance payment received. TechPark Infra has confirmed 600 sq ft Travertine Classic Beige for office renovation. Advance (₹44,100 — 50%) received on Jun 8. Material earmarked from Mumbai warehouse. Dispatch scheduled for Jun 17. Ensure quality inspection is completed before dispatch. Second-phase project (executive washrooms, ~150 sq ft) likely in August.",
    materialRequested: "Travertine Classic Beige",
    applicationArea: "Office Flooring",
    areaRequired: "600 sq ft",
    budget: "₹88,200 (confirmed)",
    createdAt: N - 28 * D,
    updatedAt: N - 5 * D,
    assignedTo: "Rohan Desai",
    activityLog: [
      { id: "a6-1", type: "system",        text: "Lead created from website inquiry form.", author: "System",       timestamp: N - 28 * D },
      { id: "a6-2", type: "stage_change",  text: "Stage moved: New Inquiry → Requirement Analysis", author: "Rohan Desai", timestamp: N - 26 * D },
      { id: "a6-3", type: "quotation_sent",text: "Quotation STN-2024-0029 (₹88,200) sent.", author: "Rohan Desai", timestamp: N - 20 * D },
      { id: "a6-4", type: "stage_change",  text: "Stage moved: Quotation Sent → Negotiation", author: "Rohan Desai", timestamp: N - 18 * D },
      { id: "a6-5", type: "call",          text: "No discount required. Deepak confirmed order. Invoice raised.", author: "Rohan Desai", timestamp: N - 10 * D },
      { id: "a6-6", type: "note",          text: "50% advance payment received (₹44,100). Transaction ID: HDFC2024061208.", author: "Rohan Desai", timestamp: N - 5 * D },
      { id: "a6-7", type: "stage_change",  text: "Stage moved: Negotiation → Confirmed", author: "Rohan Desai", timestamp: N - 5 * D },
    ],
  },
  {
    id: "l7",
    customerName: "Kavya Iyer",
    email: "kavya.iyer2024@gmail.com",
    phone: "+91 87654 32109",
    city: "Chennai",
    stage: "PROCUREMENT",
    priority: "medium",
    inquiryText: "I want Crema Marfil marble for my master bathroom renovation. Approx 350 sq ft. I have seen samples and I'm ready to order.",
    aiSummary: "Order confirmed and in active procurement. Kavya Iyer's Crema Marfil order (350 sq ft) is sourced from Chennai warehouse. BlueDart logistics pickup scheduled for Mon Jun 15. Delivery window confirmed with customer: 9–11 AM. Balance payment (₹35,000) to be collected on delivery. No outstanding issues.",
    materialRequested: "Crema Marfil Marble",
    applicationArea: "Bathroom Flooring",
    areaRequired: "350 sq ft",
    budget: "₹70,000 (confirmed)",
    createdAt: N - 35 * D,
    updatedAt: N - 3 * D,
    assignedTo: "Sneha Agarwal",
    activityLog: [
      { id: "a7-1", type: "system",        text: "Lead created from website inquiry form.", author: "System",        timestamp: N - 35 * D },
      { id: "a7-2", type: "quotation_sent",text: "Quotation STN-2024-0021 (₹70,000) sent and accepted.", author: "Sneha Agarwal", timestamp: N - 28 * D },
      { id: "a7-3", type: "note",          text: "Full payment received upfront (₹70,000). NEFT confirmation ref: KAV20240608.", author: "Sneha Agarwal", timestamp: N - 20 * D },
      { id: "a7-4", type: "stage_change",  text: "Stage moved: Confirmed → Procurement", author: "Sneha Agarwal", timestamp: N - 10 * D },
      { id: "a7-5", type: "note",          text: "Material sourced from Chennai warehouse. BlueDart pickup booked for Jun 15. Delivery slot: 9–11 AM.", author: "Sneha Agarwal", timestamp: N - 3 * D },
    ],
  },
  {
    id: "l8",
    customerName: "Raj Patel",
    company: "Patel Fine Dining",
    email: "raj@pateldining.com",
    phone: "+91 93456 78901",
    city: "Ahmedabad",
    stage: "DELIVERED",
    priority: "low",
    inquiryText: "Need sandstone flooring and limestone accent walls for restaurant renovation. Approx 900 sq ft total. Outdoor + indoor mix.",
    aiSummary: "Project successfully delivered and closed. Sandstone flooring (600 sq ft) and limestone accent walls (300 sq ft) installed at Patel Fine Dining, Ahmedabad. Customer satisfaction survey sent — awaiting response. Raj mentioned interest in a second location in Surat (≈600 sq ft) in 3 months. Strong candidate for repeat order outreach in September.",
    materialRequested: "Jaisalmer Sandstone + Travertine Limestone",
    applicationArea: "Restaurant Flooring + Wall Cladding",
    areaRequired: "900 sq ft",
    budget: "₹1,08,000 (delivered)",
    createdAt: N - 60 * D,
    updatedAt: N - 7 * D,
    assignedTo: "Rohan Desai",
    activityLog: [
      { id: "a8-1", type: "system",        text: "Lead created from referral.", author: "System",       timestamp: N - 60 * D },
      { id: "a8-2", type: "quotation_sent",text: "Quotation STN-2024-0008 (₹1,08,000) sent and confirmed.", author: "Rohan Desai", timestamp: N - 50 * D },
      { id: "a8-3", type: "note",          text: "Full payment cleared. Material dispatched from Jaipur warehouse.", author: "Rohan Desai", timestamp: N - 30 * D },
      { id: "a8-4", type: "stage_change",  text: "Stage moved: Procurement → Delivered", author: "Rohan Desai", timestamp: N - 7 * D },
      { id: "a8-5", type: "note",          text: "Delivery confirmed. Material accepted without issues. Satisfaction survey sent via WhatsApp.", author: "Rohan Desai", timestamp: N - 7 * D },
    ],
  },
];

// ─── Vendor-only products (not in public catalog) ─────────────────────────────
export const VENDOR_PRODUCTS: VendorProduct[] = [
  {
    id: "vp1",
    name: "Breccia Oniciata",
    vendorName: "Royal Marble Co.",
    materialType: "marble",
    color: "Red",
    finish: "Polished",
    thickness: "2cm",
    origin: "Italy",
    city: "Mumbai",
    vendorPrice: 280,
    unit: "sq ft",
    stockQty: 420,
    bg: "linear-gradient(135deg, rgba(140,50,30,0.4) 0%, transparent 60%), linear-gradient(155deg, #7a2010 0%, #b03020 40%, #5a1008 70%, #8a2818 100%)",
    textLight: true,
  },
  {
    id: "vp2",
    name: "Star Galaxy",
    vendorName: "Cosmos Stones Pvt. Ltd.",
    materialType: "granite",
    color: "Black",
    finish: "Polished",
    thickness: "2cm",
    origin: "India",
    city: "Bangalore",
    vendorPrice: 220,
    unit: "sq ft",
    stockQty: 650,
    bg: "radial-gradient(circle at 22% 28%, rgba(201,169,97,0.5) 0%, transparent 3%), radial-gradient(circle at 68% 62%, rgba(180,160,80,0.4) 0%, transparent 4%), radial-gradient(circle at 45% 80%, rgba(220,200,120,0.35) 0%, transparent 2.5%), linear-gradient(140deg, #080608 0%, #0e0c14 50%, #060408 100%)",
    textLight: true,
  },
  {
    id: "vp3",
    name: "Ivory Fantasy",
    vendorName: "Heritage Stone Works",
    materialType: "marble",
    color: "Cream",
    finish: "Honed",
    thickness: "1.5cm",
    origin: "Portugal",
    city: "Mumbai",
    vendorPrice: 240,
    unit: "sq ft",
    stockQty: 380,
    bg: "linear-gradient(130deg, rgba(180,150,90,0.08) 0%, transparent 55%), linear-gradient(160deg, #f4ead4 0%, #ece0c0 40%, #f8f0e0 70%, #e4d8b8 100%)",
    textLight: false,
  },
  {
    id: "vp4",
    name: "Tiger Skin",
    vendorName: "Deccan Granite Hub",
    materialType: "granite",
    color: "Brown",
    finish: "Polished",
    thickness: "2cm",
    origin: "India",
    city: "Hyderabad",
    vendorPrice: 140,
    unit: "sq ft",
    stockQty: 900,
    bg: "linear-gradient(135deg, rgba(60,30,0,0.3) 0%, rgba(120,60,0,0.15) 40%, transparent 70%), linear-gradient(145deg, #7a4000 0%, #a05010 30%, #602800 55%, #b07020 80%, #503000 100%)",
    textLight: true,
  },
  {
    id: "vp5",
    name: "Grigio Carnico",
    vendorName: "Alpine Stone Imports",
    materialType: "marble",
    color: "Gray",
    finish: "Polished",
    thickness: "2cm",
    origin: "Austria",
    city: "Delhi",
    vendorPrice: 320,
    unit: "sq ft",
    stockQty: 280,
    bg: "linear-gradient(135deg, rgba(60,60,60,0.12) 20%, transparent 60%), linear-gradient(155deg, #a0a0a0 0%, #8c8c8c 40%, #b4b4b0 70%, #909090 100%)",
    textLight: false,
  },
  {
    id: "vp6",
    name: "River Blue",
    vendorName: "Nordic Stone Corp.",
    materialType: "granite",
    color: "Blue",
    finish: "Polished",
    thickness: "2cm",
    origin: "Norway",
    city: "Mumbai",
    vendorPrice: 195,
    unit: "sq ft",
    stockQty: 480,
    bg: "radial-gradient(circle at 35% 40%, rgba(80,120,200,0.2) 0%, transparent 10%), linear-gradient(145deg, #203090 0%, #2840c0 40%, #1020a0 70%, #2840b0 100%)",
    textLight: true,
  },
  {
    id: "vp7",
    name: "Navona Bianco",
    vendorName: "Roma Marble Exports",
    materialType: "limestone",
    color: "White",
    finish: "Brushed",
    thickness: "2cm",
    origin: "Italy",
    city: "Chennai",
    vendorPrice: 175,
    unit: "sq ft",
    stockQty: 520,
    bg: "linear-gradient(160deg, #ede8e0 0%, #e0d8cc 45%, #f0ece4 70%, #d8d0c4 100%)",
    textLight: false,
  },
  {
    id: "vp8",
    name: "Magma Black",
    vendorName: "Volcan Stone India",
    materialType: "basalt",
    color: "Black",
    finish: "Textured",
    thickness: "3cm",
    origin: "India",
    city: "Pune",
    vendorPrice: 210,
    unit: "sq ft",
    stockQty: 340,
    bg: "radial-gradient(circle at 40% 55%, rgba(60,60,60,0.3) 0%, transparent 15%), linear-gradient(140deg, #141414 0%, #1c1c1c 50%, #0a0a0a 100%)",
    textLight: true,
  },
];
